/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/model/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Info */
        get: operations["model_info_model_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict */
        post: operations["predict_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predict/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Batch */
        post: operations["predict_batch_predict_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Competitions */
        get: operations["competitions_library_competitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matches */
        get: operations["matches_library_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/matches/{match_id}/shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shots For Match */
        get: operations["shots_for_match_library_matches__match_id__shots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/shots/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_library_shots_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/shots/{shot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shot Detail */
        get: operations["shot_detail_library_shots__shot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchPredictRequest */
        BatchPredictRequest: {
            /** Scenarios */
            scenarios: components["schemas"]["PredictRequest"][];
        };
        /** BatchPredictResponse */
        BatchPredictResponse: {
            /** Model Version */
            model_version: string;
            /** Predictions */
            predictions: components["schemas"]["BatchPrediction"][];
        };
        /** BatchPrediction */
        BatchPrediction: {
            /** Xg */
            xg: number;
            /** Rule */
            rule: string | null;
        };
        /**
         * BodyPart
         * @enum {string}
         */
        BodyPart: "Right Foot" | "Left Foot" | "Head" | "Other";
        /** CompetitionOut */
        CompetitionOut: {
            /** Competition Id */
            competition_id: number;
            /** Season Id */
            season_id: number;
            /** Competition Name */
            competition_name: string;
            /** Season Name */
            season_name: string;
            /** Competition Gender */
            competition_gender: string | null;
            /** N Matches */
            n_matches: number;
            /** N Shots */
            n_shots: number;
            /** Has 360 */
            has_360: boolean;
        };
        /** ExplanationItem */
        ExplanationItem: {
            /** Feature */
            feature: string;
            /** Value */
            value: number | string;
            /** Contribution */
            contribution: number;
        };
        /** FramePlayerOut */
        FramePlayerOut: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Teammate */
            teammate: boolean;
            /** Is Gk */
            is_gk: boolean;
            /** Player Id */
            player_id: number | null;
            /** Player Name */
            player_name: string | null;
            /** Position Id */
            position_id: number | null;
        };
        /** Geometry */
        Geometry: {
            /** Cone */
            cone: number[][];
            shooter_used: components["schemas"]["ShooterUsed"];
            goalkeeper_used: components["schemas"]["GoalkeeperUsed"];
            /** Players */
            players: components["schemas"]["PlayerGeometry"][];
            /** Goal Covered Intervals */
            goal_covered_intervals: number[][];
            /** Goal Free Intervals */
            goal_free_intervals: number[][];
        };
        /** GoalkeeperUsed */
        GoalkeeperUsed: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Imputed */
            imputed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Model Version */
            model_version: string;
            /** Library Loaded */
            library_loaded: boolean;
        };
        /** LibraryInfo */
        LibraryInfo: {
            /** Loaded */
            loaded: boolean;
            /** Path */
            path: string | null;
            /** N Shots */
            n_shots: number;
            /** N Matches */
            n_matches: number;
            /** N Competition Seasons */
            n_competition_seasons: number;
        };
        /** MatchOut */
        MatchOut: {
            /** Match Id */
            match_id: number;
            /** Competition Id */
            competition_id: number;
            /** Season Id */
            season_id: number;
            /** Competition Name */
            competition_name: string;
            /** Season Name */
            season_name: string;
            /** Match Date */
            match_date: string | null;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Stage */
            stage: string | null;
            /** N Shots */
            n_shots: number;
            /** N Goals */
            n_goals: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Model Version */
            model_version: string;
            /** Library */
            library: string;
            /** Library Version */
            library_version: string | null;
            /** Features */
            features: string[];
            /** Groups */
            groups: {
                [key: string]: string[];
            };
            /** Vocab */
            vocab: {
                [key: string]: string[];
            };
            /** Constants */
            constants: {
                [key: string]: unknown;
            };
            /** Penalty Xg */
            penalty_xg: number;
            /** Monotone Constraints */
            monotone_constraints: {
                [key: string]: number;
            };
            /** Training Data */
            training_data: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            shot_library: components["schemas"]["LibraryInfo"];
        };
        /**
         * PlayPattern
         * @enum {string}
         */
        PlayPattern: "Regular Play" | "From Corner" | "From Free Kick" | "From Throw In" | "From Counter" | "Other";
        /** PlayerGeometry */
        PlayerGeometry: {
            /** Kind */
            kind: string;
            /** Index */
            index: number;
            /** In Cone */
            in_cone: boolean;
            /** Distance */
            distance: number;
            /** Goal Interval */
            goal_interval: number[] | null;
        };
        /** PointIn */
        PointIn: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PredictRequest */
        PredictRequest: {
            shooter: components["schemas"]["PointIn"];
            goalkeeper?: components["schemas"]["PointIn"] | null;
            /** Defenders */
            defenders?: components["schemas"]["PointIn"][];
            /** Teammates */
            teammates?: components["schemas"]["PointIn"][];
            /** @default Right Foot */
            body_part: components["schemas"]["BodyPart"];
            /** @default Normal */
            technique: components["schemas"]["Technique"];
            /** @default Open Play */
            shot_type: components["schemas"]["ShotType"];
            /** @default Regular Play */
            play_pattern: components["schemas"]["PlayPattern"];
            /**
             * First Time
             * @default false
             */
            first_time: boolean;
            /**
             * Under Pressure
             * @default false
             */
            under_pressure: boolean;
            /**
             * One On One
             * @default false
             */
            one_on_one: boolean;
            /**
             * Open Goal
             * @default false
             */
            open_goal: boolean;
            /** @default Unknown */
            preferred_foot: components["schemas"]["PreferredFoot"];
        };
        /** PredictResponse */
        PredictResponse: {
            /** Xg */
            xg: number;
            /** Xg Raw */
            xg_raw: number;
            /** Logit */
            logit: number;
            /** Base Value Logit */
            base_value_logit: number;
            /** Model Version */
            model_version: string;
            /** Rule */
            rule: string | null;
            /** Features */
            features: {
                [key: string]: number;
            };
            /** Explanation */
            explanation: components["schemas"]["ExplanationItem"][];
            geometry: components["schemas"]["Geometry"];
        };
        /**
         * PreferredFoot
         * @enum {string}
         */
        PreferredFoot: "Right" | "Left" | "Unknown";
        /** SearchResponse */
        SearchResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["ShotSummary"][];
        };
        /** ShooterUsed */
        ShooterUsed: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Clamped */
            clamped: boolean;
        };
        /** ShotDetail */
        ShotDetail: {
            meta: components["schemas"]["ShotMeta"];
            scenario: components["schemas"]["PredictRequest"];
            prediction: components["schemas"]["PredictResponse"];
        };
        /** ShotMeta */
        ShotMeta: {
            /** Shot Id */
            shot_id: string;
            /** Match Id */
            match_id: number;
            /** Competition Id */
            competition_id: number;
            /** Season Id */
            season_id: number;
            /** Competition Name */
            competition_name: string;
            /** Season Name */
            season_name: string;
            /** Match Date */
            match_date: string | null;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Period */
            period: number | null;
            /** Minute */
            minute: number | null;
            /** Second */
            second: number | null;
            /** Team Name */
            team_name: string | null;
            /** Player Id */
            player_id: number | null;
            /** Player Name */
            player_name: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Body Part */
            body_part: string | null;
            /** Technique */
            technique: string | null;
            /** Shot Type */
            shot_type: string | null;
            /** Outcome */
            outcome: string | null;
            /** Is Goal */
            is_goal: boolean;
            /** Statsbomb Xg */
            statsbomb_xg: number | null;
            /** Xg Model */
            xg_model: number | null;
            /** Xg Diff */
            xg_diff: number | null;
            /** Weak Foot */
            weak_foot: boolean;
            /** Play Pattern */
            play_pattern: string | null;
            /** End X */
            end_x: number | null;
            /** End Y */
            end_y: number | null;
            /** End Z */
            end_z: number | null;
            /** First Time */
            first_time: boolean;
            /** One On One */
            one_on_one: boolean;
            /** Open Goal */
            open_goal: boolean;
            /** Under Pressure */
            under_pressure: boolean;
            /** Aerial Won */
            aerial_won: boolean;
            /** Deflected */
            deflected: boolean;
            /** Follows Dribble */
            follows_dribble: boolean;
            /** Redirect */
            redirect: boolean;
            /** Dominant Foot */
            dominant_foot: string;
            /** Gk Present */
            gk_present: boolean;
            /** Has Freeze Frame */
            has_freeze_frame: boolean;
            /** Model Version */
            model_version: string | null;
            /** Freeze Frame */
            freeze_frame: components["schemas"]["FramePlayerOut"][];
        };
        /** ShotSummary */
        ShotSummary: {
            /** Shot Id */
            shot_id: string;
            /** Match Id */
            match_id: number;
            /** Competition Id */
            competition_id: number;
            /** Season Id */
            season_id: number;
            /** Competition Name */
            competition_name: string;
            /** Season Name */
            season_name: string;
            /** Match Date */
            match_date: string | null;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
            /** Period */
            period: number | null;
            /** Minute */
            minute: number | null;
            /** Second */
            second: number | null;
            /** Team Name */
            team_name: string | null;
            /** Player Id */
            player_id: number | null;
            /** Player Name */
            player_name: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Body Part */
            body_part: string | null;
            /** Technique */
            technique: string | null;
            /** Shot Type */
            shot_type: string | null;
            /** Outcome */
            outcome: string | null;
            /** Is Goal */
            is_goal: boolean;
            /** Statsbomb Xg */
            statsbomb_xg: number | null;
            /** Xg Model */
            xg_model: number | null;
            /** Xg Diff */
            xg_diff: number | null;
            /** Weak Foot */
            weak_foot: boolean;
        };
        /**
         * ShotType
         * @enum {string}
         */
        ShotType: "Open Play" | "Free Kick" | "Corner" | "Penalty";
        /**
         * Technique
         * @enum {string}
         */
        Technique: "Normal" | "Volley" | "Half Volley" | "Lob" | "Backheel" | "Overhead Kick" | "Diving Header";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    model_info_model_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"];
                };
            };
        };
    };
    predict_predict_post: {
        parameters: {
            query?: {
                /** @description include additive log-odds contributions */
                explain?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_batch_predict_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPredictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPredictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    competitions_library_competitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionOut"][];
                };
            };
        };
    };
    matches_library_matches_get: {
        parameters: {
            query: {
                competition_id: number;
                season_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shots_for_match_library_matches__match_id__shots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_library_shots_search_get: {
        parameters: {
            query?: {
                preset?: string | null;
                player?: string | null;
                competition_id?: number | null;
                season_id?: number | null;
                match_id?: number | null;
                outcome?: string | null;
                body_part?: string | null;
                technique?: string | null;
                min_xg?: number | null;
                max_xg?: number | null;
                min_sb_xg?: number | null;
                max_sb_xg?: number | null;
                sort?: string | null;
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shot_detail_library_shots__shot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
